library(bio3d)
library(igraph)
pdb <- read.pdb("md.pdb")
modes <- nma(pdb)
cij <- dccm(modes)
defe <- deformation.nma(modes)
defesums <- rowSums(defe$ei[,1:3])
flucts <- fluct.nma(modes, mode.inds=seq(7,9))
write.pdb(pdb=NULL, xyz=modes$xyz, file="R-defact.pdb", b=defesums)
write.pdb(pdb=NULL, xyz=modes$xyz, file="R-deflut.pdb", b=flucts)
net <- cna(cij, cutoff.cij=0.2)
png("full-net.png")
plot(net, pdb, full=TRUE, vertex.label.cex=0.7)
dev.off()
png("simple-net.png")
plot(net, pdb)
dev.off()
vmd.cna(net, pdb, launch=TRUE, radius = table(net$communities$membership)/10)
q()
